name: Deploy Airly Staging

on:
  push:
    branches:
      - staging 

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging 
      - name: deploy Airly staging
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.UPDATE_STAGGING_IP }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.KEY}}
          port: ${{ secrets.SSH_PORT }}
          script: ./airly.sh
